name: Deploy Static Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Upload everything in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
